//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUtau.Plugin.Builtin.Data {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenUtau.Plugin.Builtin.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] arpasing_template {
            get {
                object obj = ResourceManager.GetObject("arpasing_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] de_vccv_template {
            get {
                object obj = ResourceManager.GetObject("de_vccv_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] envccv_template {
            get {
                object obj = ResourceManager.GetObject("envccv_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] en_cPv_template {
            get {
                object obj = ResourceManager.GetObject("en_cPv_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] en_xsampa_template {
            get {
                object obj = ResourceManager.GetObject("en_xsampa_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] filipino_template {
            get {
                object obj = ResourceManager.GetObject("filipino_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] german_template {
            get {
                object obj = ResourceManager.GetObject("german_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kocv_template {
            get {
                object obj = ResourceManager.GetObject("kocv_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] njokis_template {
            get {
                object obj = ResourceManager.GetObject("njokis_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] generic_syllabic_template {
            get {
                object obj = ResourceManager.GetObject("generic_syllabic_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
